version: '3.5'

services:
  postgresql:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_DB: "scrapper"
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend



  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=qwerty
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend


volumes:
  postgres:

networks:
  backend:
    driver: bridge