global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
#  - job_name: 'prometheus'
#
#    scrape_interval: 5s
#
#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: 'scrapper'

    metrics_path: '/metrics'

    scrape_interval: 5s

    static_configs:
      - targets: [ 'host.docker.internal:8085' ]

  - job_name: 'bot'

    metrics_path: '/metrics'

    scrape_interval: 5s

    static_configs:
      - targets: [ 'host.docker.internal:8084' ]
